### ISSUE TITLE
logstash-forwarder wrongly hangs forever when using STDIN via "paths": [ "-" ]

### ISSUE THREAD

**Issue by rnavarr** [elasticsearch/logstash-forwarder#343] opened 2015-01-09 01:45 UTC
As commented within issue #251, the logstash-forwarder hangs forever when run as:
print '' | /opt/logstash-forwarder/bin/logstash-forwarder -config logstash-fwd-mysql-slowquery.conf

with config containing: 
"files": [
    {
      "paths": [ "-" ],
      "fields": { "type": "mysql-slowquery-log" }
    }
  ]

Please review code for sections that wrongly treat a pipe (STDIN) too much like a file and try to seek.

/var/log/messages reports:
2015/01/09 01:37:28.196532 File truncated, seeking to beginning: -

which seems to indicate an incorrect attempt to seek on STDIN !!

**Comment by driskell** [comment] 2015-01-09 06:47
@rnavarr I think that is a bug yes. It should just stop reading from stdin with no message. I'm sure it did this before.

The hanging will remain tho by design I think as what would it do if there was other files being monitored from config file? #251 mentions using cmdline instead of config file for stdin and only read stdin so it's safe. I'd be all for that too. Would just break compatibility with old configs using "-" path.

**Comment by rnavarr** [comment] 2015-01-09 18:17
Hiya,
Thank you for responding so quickly. Was just deciding what to do next - revert back to logstash :-(

It seems to me that when mentioned within configs, files are treated a little as pipelines of data. Software then simulates a pipeline in a file by remembering last place and starting from there. There seems an in built assumption that as long as the file is there the program should continue to watch it for additional bytes.

On the other hand, using Unix/Linux pipes and reading from STDIN really *is* a pipe. Pipes have an end if their data ends and no end if the data is without end (like streaming logs from a 24x7  RDBMS).

This seems to introduce a design asymmetry ... if there are multiple input sources how should the forwarder behave if one naturally terminates and the others never do?...

Am certain that hanging for ever on a STDIN read once the writer has closed is always wrong. I do not know how hard that asymmetry is to percolate through the shared file/pipe logic. But I suggest just closing and no longer reading from STDIN once the writer signals it has finished for ever. You can keep the same config syntax just no longer read from STDIN once you get a close on it.

**Comment by jordansissel** [comment] 2015-01-09 23:58
I'm in the car right now, so I can't confirm, but I can confirm that if the *only* path being watched is stdin, then lsf should terminate after stdin closes. If it doesn't terminate on that condition, it's a bug.

**Comment by rnavarr** [comment] 2015-01-12 20:03
OK, agreed. So in the absence of a logstash-forwarder update let me try log-courier. Thanks driskell for the opportunity to try an update so quickly!

**Comment by jordansissel** [comment] 2015-02-10 21:17
@rnavarr if this is solved for you, then I will close it.

**Closed by jordansissel** 2015-02-10 21:17 UTC

**Comment by rnavarr** [comment] 2015-02-11 00:34
I gave up on logstash-forwarder and log-courier for the time being as I ran out of time to figure out how to download and install the latest image. Instead use full version of slow logstash. Will wait until this feature is fixed in logstash-forwarder.

Are you saying that it is not worth removing the infinite hang on EOF when reading from STDIN/pipe?

**Comment by TJC** [comment] 2015-03-30 06:26
This bug still seems to be present in logstash-forwarder. Can the bug be re-opened?

**Comment by relgames** [comment] 2015-06-01 17:35
Hi @jordansissel, the issue is still here. Are there plans to fix it, or should I switch to log-courier?

**Comment by cgianelle** [comment] 2015-08-27 16:32
Yeah, I am seeing this issue as well:
cat somelog.log | logstash-forwarder -config some_config.conf; rm somelog.log
and 
logstash-forwarder -config some_config.conf < somelog.log; rm somelog.log
both have the same result, logstash-forwarder processes somelog.log, but then never exits after completing the processing.

**Comment by Tuxdude** [comment] 2015-09-13 23:28
I had the same issue with logstash-forwarder, when its config is monitoring only for STDIN. Once the pipe is closed, it would be nice if logstash-forwarder exits.

I have cases where I use docker as a container to run one of my service and redirect all logs (by piping) into LSF. If my process crashes for some reason, LSF should also exit but it doesn't because of this issue.

For now, I've switched to log-courier which does not have this issue, but it would be nice is LSF had this feature :)
