### ISSUE TITLE
client logs unchanging,but repeatedly send the same logs to logstash server

### ISSUE THREAD

**Issue by hnucsbjd** [elasticsearch/logstash-forwarder#131] opened 2013-12-06 06:19 UTC
the newest logstash-forwarder master branch, client's logs unchanging,but repeatedly send the same logs to logstash server.for example, new a hadoop-datanode-test2.log file and add two lines logs text by hands,logstash-forwarder client can discover the logs,but send the same logs repeatedly,never stop.
hadoop-datanode-test2.log file content:
2013-11-18 16:19:53,939 [ERROR][ContainerBackgroundProcessor[StandardEngine[Catalina]]] Context initialization failed (org.springframework.web.context.ContextLoader:ContextLoader.java:225) 
2013-11-18 16:19:53,939 [ERROR][ContainerBackgroundProcessor[StandardEngine[Catalina]]] 	

logstash-forwarder sent the same logs repeatedly,logstash-forwarder.log:
2013/12/06 13:36:49.964047 File truncated, seeking to beginning: /home/honki/dev/logstash/hadoop-datanode-test2.log
2013/12/06 13:36:51.397188 Registrar received 4 events
2013/12/06 13:36:59.965654 File truncated, seeking to beginning: /home/honki/dev/logstash/hadoop-datanode-test2.log
2013/12/06 13:37:01.401528 Registrar received 4 events
2013/12/06 13:37:09.967999 File truncated, seeking to beginning: /home/honki/dev/logstash/hadoop-datanode-test2.log
2013/12/06 13:37:11.395816 Registrar received 4 events
2013/12/06 13:37:19.970475 File truncated, seeking to beginning: /home/honki/dev/logstash/hadoop-datanode-test2.log
2013/12/06 13:37:21.396515 Registrar received 4 events
2013/12/06 13:37:29.972853 File truncated, seeking to beginning: /home/honki/dev/logstash/hadoop-datanode-test2.log
2013/12/06 13:37:31.396595 Registrar received 4 events
2013/12/06 13:37:39.975221 File truncated, seeking to beginning: /home/honki/dev/logstash/hadoop-datanode-test2.log
2013/12/06 13:37:41.395678 Registrar received 4 events

logstash server get the same logs repeatedly:
2013-11-18 16:19:53,939 [ERROR][ContainerBackgroundProcessor[StandardEngine[Catalina]]] Context initialization failed (org.springframework.web.context.ContextLoader:ContextLoader.java:225)
2013-11-18 16:19:53,939 [ERROR][ContainerBackgroundProcessor[StandardEngine[Catalina]]] 

2013-11-18 16:19:53,939 [ERROR][ContainerBackgroundProcessor[StandardEngine[Catalina]]] Context initialization failed (org.springframework.web.context.ContextLoader:ContextLoader.java:225)
2013-11-18 16:19:53,939 [ERROR][ContainerBackgroundProcessor[StandardEngine[Catalina]]] 

2013-11-18 16:19:53,939 [ERROR][ContainerBackgroundProcessor[StandardEngine[Catalina]]] Context initialization failed (org.springframework.web.context.ContextLoader:ContextLoader.java:225)
2013-11-18 16:19:53,939 [ERROR][ContainerBackgroundProcessor[StandardEngine[Catalina]]] 

server$ java -jar logstash-1.2.2-flatjar.jar agent -f central.conf:
input{
lumberjack {
host=>"localhost"
port => "6782"
codec => multiline {
      pattern => "^\D"
      what => "previous"
 }
ssl_certificate => "/home/honki/dev/logstash/server.crt"
ssl_key => "/home/honki/dev/logstash/server.key"
type => "lumberjack"
}
}
output {
elasticsearch {
 host => "localhost"
}
}

client$ bin/logstash-forwarder -config logstash-forwarder.conf:
{
"network":{
"servers":["localhost:6782"],
"ssl ca":"/opt/logstash-forwarder/server.crt",
"timeout":15
},
"files":[
{
"paths": [
"/home/honki/dev/logstash/hadoop-datanode-test2.log"
],
"fields": { "type": "datalog" }
}

**Comment by jordansissel** [comment] 2015-03-04 00:48
If this was a bug, I think it's fixed in master and will appear in the next release (0.4.0).

If it's not a bug, retransmission can occur due to a downstream server failure (or network error) causing lsf to retransmit the current payload while trying to get acknowledgement from Logstahs.

**Closed by jordansissel** 2015-03-04 00:48 UTC
